### ISSUE TITLE
TO-DO fixes and improvement

### ISSUE THREAD

**Issue by keselekpermen69** [Sana-Project/UserButt#3]
- [ ] (PYL-E0102) Fix redefined function 
- [ ] Handle all exception
- [ ] Update and push to heroku from different branch
- [ ] Catch exception if alive logo isn't a direct link
- [ ] Fix .uploadas thumnail
